Feature/sprint95 pinned message
stationfy/arena-chat-sdk pull request #23
Opened 2020-12-02 16:36 UTC by Thrashattack

Adds fetch channel pin message to chat sdk

2020-12-03 12:33 UTC, cesarwbr requested changes
It's missing the tests for these two files

2020-12-07 17:11 UTC, fboechats approved these changes

2020-12-07 17:32 UTC, cesarwbr approved these changes
ok

2021-01-15 13:25 UTC, cesarwbr commented on packages/sdk/src/channel/channel.ts
> +      const { GraphQLAPI } = await import('../services/graphql-api');
you should use the current graphql instance `this.graphQLAPI`

2021-01-15 13:25 UTC, cesarwbr commented on packages/sdk/src/channel/channel.ts
> +    if (this.sdk.user === null) {
the pin message should be available for anonymous user

2021-01-15 13:27 UTC, cesarwbr requested changes
check the messages

2021-01-15 17:10 UTC, cesarwbr approved these changes
ok

2021-01-15 19:07 UTC, merged